## 创建ndarray对象
通过 NumPy 的内置函数 array() 可以创建 ndarray 对象，其语法格式如下：

<b>numpy.array(object, dtype = None, copy = True, order = None,subok=False,ndmin = 0)</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | object| 表示一个数组序列。       |
| 2   | dtype | 可选参数，通过它可以更改数组的数据类型。        |
| 3      | copy | 可选参数，表示数组能否被复制(深拷贝)，默认是 True。        |
| 4      | ndmin |  用于指定数组的维度。       |
| 5      | subok |  可选参数，类型为bool值，默认False。为True，使用object的内部数据类型；False：使用object数组的数据类型。|

In [2]:
import numpy as np
# 创建ndarray对象

In [3]:
# 可以使用任何序列类型数据进行生成对象.
np.array([1, 2, 3, 4, 5])  # 使用list生成对象.

array([1, 2, 3, 4, 5])

In [4]:
np.array([i for i in range(10)])  # 使用生成器生成ndarray序列.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 列表中元素不相同的情况
np.array([1, 2, 3, 4, 5, 'a'])
# 统一转换成占用内存最大的那种数据类型. 这里就是U11

array(['1', '2', '3', '4', '5', 'a'], dtype='<U11')

In [6]:
# np.array()参数练习
# dtype: 指定数据类型
a = np.array([1, 2, 3], dtype=np.float32)
# 类型为float32.
a  # array([1., 2., 3.], dtype=float32)
print(a.dtype)

b = np.array([1, 2, 3], dtype="float")  # 默认是float
b  # array([1., 2., 3.], dtype=float64)
print(b.dtype)  # float64

float32
float64


In [7]:
# 设置copy参数， 默认为True
a = np.array([1, 2, 3, 4, 5])
b = np.array(a)  # 从a复制给b
print(f"id(a):{id(a)}, id(b):{id(b)}")  # 可见, id不同, 因此不是一个数组

b[0] = 10  # 修改b元素
print(b)
print(a)  # 可见, a与b无关

id(a):3059561956816, id(b):3059561856144
[10  2  3  4  5]
[1 2 3 4 5]


In [8]:
# 当设置copy参数为False时
a = np.array([1, 2, 3, 4, 5])
b = np.array(a, copy=False)  # 创建的时候不复制, 不会创建副本, 即,b同样指向a的区域.
print(f"id(a):{id(a)}, id(b):{id(b)}")  # 可见, id不同, 因此不是一个数组


id(a):3059561957296, id(b):3059561957296


In [9]:
# ndmin: 用于指定数组的维度
a = np.array([1, 2, 3], ndmin=2)
a.ndim  # 2维度

2

In [10]:
# subok参数: 类型为bool值, 默认为False为True, 使用object内部的数据类型, False: 使用object数组的数据类型
a = np.mat([1, 2, 3, 4]) # 创建矩阵对象
print(type(a)) # <class 'numpy.matrix'>

at = np.array(a, subok=True)
af = np.array(a, subok=False)
print('subok=True', type(at)) # subok=True <class 'numpy.matrix'> # 使用object类型作为数据类型
print('subok=False', type(af)) # subok=False <class 'numpy.ndarray'> # 仅仅使用ndarray作为数据类型



<class 'numpy.matrix'>
subok=True <class 'numpy.matrix'>
subok=False <class 'numpy.ndarray'>


In [13]:
# 复制数组
a = np.array([2, 3, 4 ,5 ])
# 从a定义b时候, 有几种方案:
b  = np.array(a)
print(id(a), id(b)) # 不同

# 使用.copy()方法
c = a.copy()
print(id(a), id(c)) # 不同

# 这些都是深拷贝, 也就是数据拷贝, 不是地址拷贝

3059577016016 3059321312624
3059577016016 3059561956624


In [ ]:
# argnge()生成区间数组
# 与range()类似, 不过返回对象是ndarray类型