## 创建ndarray对象
通过 NumPy 的内置函数 array() 可以创建 ndarray 对象，其语法格式如下：

<b>numpy.array(object, dtype = None, copy = True, order = None,subok=False,ndmin = 0)</b>

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | object| 表示一个数组序列。       |
| 2   | dtype | 可选参数，通过它可以更改数组的数据类型。        |
| 3      | copy | 可选参数，表示数组能否被复制(深拷贝)，默认是 True。        |
| 4      | ndmin |  用于指定数组的维度。       |
| 5      | subok |  可选参数，类型为bool值，默认False。为True，使用object的内部数据类型；False：使用object数组的数据类型。|

In [1]:
import numpy as np
# 创建ndarray对象

In [2]:
# 可以使用任何序列 类型数据进行生成对象.
np.array([1, 2, 3, 4, 5])  # 使用list生成对象.

array([1, 2, 3, 4, 5])

In [3]:
np.array([i for i in range(10)])  # 使用生成器生成ndarray序列.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 列表中元素不相同的情况
np.array([1, 2, 3, 4, 5, 'a'])
# 统一转换成占用内存最大的那种数据类型. 这里就是U11

array(['1', '2', '3', '4', '5', 'a'], dtype='<U11')

In [5]:
# np.array()参数练习
# dtype: 指定数据类型
a = np.array([1, 2, 3], dtype=np.float32)
# 类型为float32.
a  # array([1., 2., 3.], dtype=float32)
print(a.dtype)

b = np.array([1, 2, 3], dtype="float")  # 默认是float
b  # array([1., 2., 3.], dtype=float64)
print(b.dtype)  # float64

float32
float64


In [6]:
# 设置copy参数， 默认为True
a = np.array([1, 2, 3, 4, 5])
b = np.array(a)  # 从a复制给b
print(f"id(a):{id(a)}, id(b):{id(b)}")  # 可见, id不同, 因此不是一个数组

b[0] = 10  # 修改b元素
print(b)
print(a)  # 可见, a与b无关

id(a):1899463176912, id(b):1899463080816
[10  2  3  4  5]
[1 2 3 4 5]


In [7]:
# 当设置copy参数为False时
a = np.array([1, 2, 3, 4, 5])
b = np.array(a, copy=False)  # 创建的时候不复制, 不会创建副本, 即,b同样指向a的区域.
print(f"id(a):{id(a)}, id(b):{id(b)}")  # 可见, id不同, 因此不是一个数组


id(a):1899463178928, id(b):1899463178928


In [8]:
# ndmin: 用于指定数组的维度
a = np.array([1, 2, 3], ndmin=2)
a.ndim  # 2维度

2

In [9]:
# subok参数: 类型为bool值, 默认为False为True, 使用object内部的数据类型, False: 使用object数组的数据类型
a = np.mat([1, 2, 3, 4]) # 创建矩阵对象
print(type(a)) # <class 'numpy.matrix'>

at = np.array(a, subok=True)
af = np.array(a, subok=False)
print('subok=True', type(at)) # subok=True <class 'numpy.matrix'> # 使用object类型作为数据类型
print('subok=False', type(af)) # subok=False <class 'numpy.ndarray'> # 仅仅使用ndarray作为数据类型



<class 'numpy.matrix'>
subok=True <class 'numpy.matrix'>
subok=False <class 'numpy.ndarray'>


In [10]:
# 复制数组
a = np.array([2, 3, 4 ,5 ])
# 从a定义b时候, 有几种方案:
b  = np.array(a)
print(id(a), id(b)) # 不同

# 使用.copy()方法
c = a.copy()
print(id(a), id(c)) # 不同

# 这些都是深拷贝, 也就是数据拷贝, 不是地址拷贝

1899463178064 1899463178736
1899463178064 1899463178928


In [11]:
# 练习:
# 创建一个1维数组
a = np.array([1, 2,], ndmin=1)
print(a)

# 创建一个2维数组
b = np.array([1, ], ndmin=2)
print(b.ndim)

# 创建嵌套序列不一样的数组,
c = np.array([[1,  2, 3], [1, 2]])
print(c) # [list([1, 2, 3]) list([1, 2])] # see, is a 1 dimension
print(c.ndim) # 1

# 测试数组a, 将数组赋给b,修改b,观察a是否发生变化.
b = np.array(a, copy=True)
print(b)

[1 2]
2
[list([1, 2, 3]) list([1, 2])]
1
[1 2]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_7912\3015915134.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = np.array([[1,  2, 3], [1, 2]])


In [22]:
# arange()生成区间数组
# 与range()类似, 不过返回对象是ndarray类型
# 使用方法:
# arange(start=None, end, step=1, dtype)
# 包前不包后
# arange([start,] stop[, step,], dtype=None, *, like=None) # 可见, start和step都是非必要参数
print(np.arange(10)) # [0 1 2 3 4 5 6 7 8 9]







[0 1 2 3 4 5 6 7 8 9]


In [27]:
# 支持使用浮点型数据
np.arange(3.1)
# 可见start=0, step=1 (默认情况下)

array([0., 1., 2., 3.])

In [28]:
# 在cpython中的range()就不支持浮点数数据
# range(3.1) # 'float' object cannot be interpreted as an integer

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
# arange指定数据类型
a = np.arange(5, dtype=np.float32)
print(a) # [0. 1. 2. 3. 4.]
print(a.dtype) #


[0. 1. 2. 3. 4.]
float32


In [53]:
# 参数
np.arange(10, 40, 2)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [59]:
# 默认两个参数
ar2 = np.arange(20, 3)
print(ar2)
# 正确, 但是是[] 也就是没有返回任何值, 从20, 到3, 显然不满足向左的原则. 因此也就没有返回任何元素

# 正确的书写格式
ar2 = np.arange(0, 20, 3)
print(ar2) # [ 0  3  6  9 12 15 18]

[]
[ 0  3  6  9 12 15 18]


In [60]:
# jupyter中有趣的特性 -> 如果数组过长或者显示不下, 那么jupyter就会省略中间数值, 只展示开头和结尾
np.array(10000)

array(10000)

In [62]:
# 如何防止float的不精确, 印象到np.arange()
# look a instance:
ar = np.arange(0.1, 0.4, 0.1)
print(ar) # [0.1 0.2 0.3 0.4]
# 可见, 从0.1开始到0.4结束, step is 01, 但是本应不包含0.4, 但这里却包含了, 这是因为float的存储是不精确的. 因此使用这种方法无法准确的获取我们想要的序列.
#
# 因此引出np.linspace()创建等差数列.
#

[0.1 0.2 0.3 0.4]


In [66]:
# linspace()创建等差数列
# 使用
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# 在[start, stop] 中等间隔划分num个点, endpoint表示是否包含stop, retstep表示是否显示间距, dtype表示数据类型

# 使用案例:
a = np.linspace(1, 50)
print(a) # 可见, 默认是被分成了50等份
# see, default it Separated 50
print(a.dtype) # float64

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
float64


In [69]:
# num参数, 也就是在间隔内有多少个点
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [71]:
# endpoint: 默认为True, 是否包含最后截至点, 默认包含
a = np.linspace(1, 10, 10, endpoint=False)
print(a) # 可见, 此时就不包含10 stop 了.

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [76]:
# 设置retstop显示不长
tuple_ar_step = np.linspace(1, 10, 10, retstep=True)
print(tuple_ar_step)
print(type(tuple_ar_step)) # 可见是元组类型
# 第一个元素是ndarray, 第二个元素是步长

print('=' * 40)

array, step = np.linspace(2, 6, 9, retstep=True)
print(array)
print(step)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
<class 'tuple'>
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
0.5
