In [2]:
import numpy as np



In [4]:
dt = np.dtype(np.uint32)

print(dt)
print(type(dt))

uint32
<class 'numpy.dtype[uint32]'>


In [6]:
# 每一个类型都有其唯一一个对应的标识符.

dt = np.dtype('i4')

print(dt)
print(type(dt))

int32
<class 'numpy.dtype[int32]'>


In [7]:

dt = np.dtype("<i4") # 就表示以小端方式存储的int32类型

print(dt)
print(type(dt))


int32
<class 'numpy.dtype[int32]'>


In [12]:

student = np.dtype([("name", "S20"), ("age", "i4"), ("marks", "f4")]) # 这就是结构化数据.

print(student)

[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')]


In [31]:


# 创建Ndarray数组对象.
# numpy默认ndarray的所有元素的类型是相同的, 这一点与python中的list不同, 如果传进来的列表中包含不同的类型, 则统一为同一类型, 优先级: str>float>int

# np.array(object, dtype, copy=True, order=None, subok=False, ndmin=0)
# object: 数组或者嵌套的列表.
# dtype: 数组元素的数据类型, 可选.
# copy: 对象是都需要复制.
# order: 创建数组的央视, C:行方向, F:列方向, A任意方向(default)
# subok: 默认返回一个与基类类型一致的数组
# ndmin: 指定生成数组的最小维度.



In [33]:

# 创建一维度数组
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
# 元素类型相同

arr = np.array([1, 2, 3, 4, 5.0, 6, 7, 8, 9])
print(arr)
# 都变成浮点数了, 这其中有一个优先级的问题.

print(type(arr))



[1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [36]:
# 多维数组.
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [38]:
arr = np.array([1, 2, 3], ndmin=2) # 规定最小维度为2
print(arr)
print(arr.shape)

arr


[[1 2 3]]
(1, 3)


array([[1, 2, 3]])

In [43]:
# dtype参数:
arr = np.array([1, 2, 3 ,4 ,5], dtype=np.float32)

print(arr)

[1. 2. 3. 4. 5.]


In [44]:
arr = np.array([1, 2, 3 ,4 ,5], dtype='f')
# 底层创建一个dtype对象, 然后开辟空间.
print(arr)

[1. 2. 3. 4. 5.]


In [53]:
# 结构化数据类型
student = np.dtype([("name", "S20"), ("age", "i4"), ("marks", "f4")]) # dtype对象.

print(student)

arr = np.array([("jack", 18, 98.0), ("kaige", 17, 09.8)], dtype=student)
arr


[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')]


array([(b'jack', 18, 98. ), (b'kaige', 17,  9.8)],
      dtype=[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')])

In [55]:

# asarray()函数:
# np.asarray(a, dtype=None, order=None)
# a任意形式的输入参数, 可以是各种迭代嵌套. 元组, 列表, 列表的列表, 多为数组.
# 返回ndarray对象.

arr = np.asarray([1, 2, 3, 4, 5])


In [56]:
arr = np.asarray([(1, 2, 3), (4, 5, 6)])
arr

# 一般使用asarray, 改变已有ndarray类型.


array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
# 一些创建数组对象的函数:
# empty(shape, dtype, order)
# 创建一个指定shape, dtype, 且未初始化的数组.
# shape: 数组形状.
#
import numpy as np
arr = np.empty((3, 2), dtype=np.int32) # 3row, 2col.o

arr # 未初始化, 其中的值是随意的.




array([[247272048,     32761],
       [247279520,     32761],
       [247274816,     32761]])

In [64]:
# zeros(shape, dtype=None, order=None)
# 创建shape大小的全0数组.

arr = np.zeros(5, dtype=np.int32)
print(arr)

arr = np.zeros((3, 2), dtype=[("x", "i4"), ("y", 'f')]) # 结构化数据, 进行zeros. 也是如此.
print(arr)

[0 0 0 0 0]
[[(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]
 [(0, 0.) (0, 0.)]]


In [65]:
# ones()
# 创建shape大小的全1数组.
arr = np.ones((3, 2))

print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [69]:
# full(shape, fill_value, dtype=None, order='C')
# 创建指定形状的数组, 用fill_value填充.
arr = np.full((5, 1), fill_value=1024)
print(arr)

[[1024]
 [1024]
 [1024]
 [1024]
 [1024]]


In [70]:

# eye(N, M=None, k=0, dtype=None, order='C')
# 对角线为1, 其他为0.
# N: 行数
# M: 列数, 默认等于行数, 可选.
# dtype: 数据类型, 可选.
arr = np.eye(10)

print(arr)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [73]:
# arange(start, stop, step, dtype)
# 类似于range. 生成序列 ndarray对象.
# start=0.
# stop # 不包含
# step=1, 步长.

arr = np.arange(1, 11, 1)

print(arr)
# 不包含11.



[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
# frombuffer(buffer, dtype=float, count=-1, offset=0)
# 用于实现动态数组, 接受buffer输入参数, 以流的形式读入转化成ndarray对象.
# buffer是字符串类型的时候, python3默认str是unicode类型, 所以要转成bytestring在原str前加上b.