In [13]:
import numpy as np

In [14]:
arr = np.arange(10)
print(arr)
arr[2]

[0 1 2 3 4 5 6 7 8 9]


2

In [15]:
# 切片, 我们通过创建一个slice对象, 然后直接使用索引对array进行切片.#
s = slice(2, 7, 1)
print(s)
print(arr[s])

slice(2, 7, 1)
[2 3 4 5 6]


In [16]:
# 或者使用索引中的::来进行切片.
# 举例:
arr = np.arange(15)
arr.shape = (3, 5)  # 显示修改shape属性, 与reshape修改是一样的
# arr.shape <==> np.reshape(arr, (3, 5))
print(arr)  #
print('\n')
print(arr[1]) # 也就是取出第一个元素.

print("\n")
print(arr[0, 1: 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[5 6 7 8 9]


[1 2 3]


In [17]:
# 切片包括省略号..., 来选择元组的长度与数组的维度相同. 如果在行位置使用省略号, 他将返回包含行中元素的ndarray.
# 其实就表示所有. 也就是这一维度上所有的元素.拿出来.

print(arr)
print(arr[..., 0: 3])
print(arr[1, ...])
# 所以...充当是:的作用, 也就是前面所有的元素.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
[5 6 7 8 9]


In [18]:
# 高级索引.
# ndarray还提供了由整数数组索引、布尔索引。

import numpy as np

arr = np.arange(9)
arr.shape = (3, 3) # 直接修改

print(arr)

print(arr[[0, 1, 2], [0, 1, 0]])
# 0行第0个元素, 1行1个元素, 2行0元素.就是这些

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 6]


In [19]:
arr = np.arange(12)
arr.shape = (4, 3)
print(arr)
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

print("\n")

print(arr[rows, cols])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  2]
 [ 9 11]]


In [20]:
# 实验
rows = np.array([0, 0, 3, 3])
cols = np.array([0, 2, 0, 2])

print(arr[rows, cols])


# 所以, 最终的形状, 与你如何索引有关.

[ 0  2  9 11]


In [21]:
# 借助..., :来进行数组切片.
print(arr)
print("\n")



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
# 布尔索引, 通过布尔运算, 如比较运算符, 来获取符合指定条件的元素的数组.
print(arr[arr > 5])

[ 6  7  8  9 10 11]


In [24]:
arr = np.array([np.nan, 1, 1, 2, np.nan])
print(np.isnan(arr))
print(arr[~np.isnan(arr)])

[ True False False False  True]
[1. 1. 2.]
