In [6]:
# 连接数组. 相关操作 # 四种方式.
import numpy as np

# np.concatenate([a1, a2, ...], axis)
# 相同类型的数组的集合. (注意, array必须是相同形状的)
# axis: 沿着它连接数组的轴, 默认0.

a = np.arange(4).reshape((2, 2))
b = np.arange(4, 8).reshape((2, 2))

print(a, "\n\n", b)

print(np.concatenate([a, b], axis=0))


[[0 1]
 [2 3]] 

 [[4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [8]:
print(np.concatenate([a, b], axis=1)) # 等同于hstack方法.

[[0 1 4 5]
 [2 3 6 7]]


In [ ]:
# a = n

In [13]:
# stack(arrays, axis)
# arrays: 相同形状的数组序列.
# axis: 数组中的轴, 输入数组沿着axis进行堆叠.
a = np.arange(4).reshape((2, 2))
b = np.arange(4, 8).reshape((2, 2))

print(a, "\n\n", b)
print("\n")
c = np.stack([a, b], axis=0) # 按照axis=0进行堆叠. 就是相叠起来.
print(c.shape, c.ndim) # 变成3维的.

d = np.stack([a, b], axis=1)
print(d)

[[0 1]
 [2 3]] 

 [[4 5]
 [6 7]]


(2, 2, 2) 3
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


In [15]:
# hstack(arrays) # 是stack函数的变种, 它通过水平堆叠来生成数组.
# 维度不增加, 只是在水平方向进行stack堆叠.

a = np.arange(4).reshape((2, 2))
b = np.arange(4, 8).reshape((2, 2))

c = np.hstack([a, b])
print(c.shape, c.ndim)
print(c) # 就是水平方向进行堆叠, 前提必须是形状相同.

(2, 4) 2
[[0 1 4 5]
 [2 3 6 7]]


In [17]:
# 同理: vstack. # 就是沿着垂直进行堆叠.
a = np.arange(4).reshape((2, 2))
b = np.arange(4, 8).reshape((2, 2))

c = np.vstack([a, b])
print(c.shape, c.ndim)
print(c)

(4, 2) 2
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [2]:
# 分割数组：
# np.split(ary, indices_or_sections, axis=0)
# 作用, 函数沿特定的轴将数组切分为子数组.
# ary: 被分割的数组
# indices_or_sections: 是一个整数, 就用该数平均切分, 如果是一个数组, 为沿轴切分的位置. 分成几份, 以及索引分
# axis: 沿着哪个维度进行切分, 默认为0, 横向切分. 为1, 纵向切分.


import numpy as np

x = np.arange(12)

a = np.split(x, 3)
print(a)


a = np.split(x, [2, 5]) # 就是从索引为2, 5进行分割
print(a)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0, 1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]


In [5]:
x = np.arange(12).reshape((3, 4))

print(x)
print("\n")



a = np.split(x, 3)
# 以一行为一个元素, 因为axis=0..
print(a)


a = np.split(x, 2, 1) # 按照列来切.
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [7]:
# hsplit()
# 用于水平分割数组, 通过指定要返回的相同形状的数组来拆分原数组.
# 相当于split axis=1的情况, 将列进行切割.
x = np.arange(12).reshape((2, 6))
print(x)
a = np.hsplit(x, 3)
print(a)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [10]:
a = np.vsplit(x, 2)
print(a)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]


In [12]:
# 数组元素的添加与删除:

# resize(arr, shape)
# arr: 数组
# shape: 返回数组新的形状.

import numpy as np

x = np.arange(6).reshape(2, 3)
print(x)
print("\n")


y = np.resize(x, (3, 2))
print(y) # 按照内存中的存放来看待.



z = np.resize(x, (3, 3))
print(z) # 他会将x中的元素进行重复.







[[0 1 2]
 [3 4 5]]


[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]]
