In [1]:
# 函数
# 字符串函数：是用于dtype为numpy.string_或者numpy.unicode_的数组执行向量化字符串操作.
# 字符串函数基于python内置库当中的标准字符串函数在字符数组类(numpy.char)中定义. 也就是所有的操作都在numpy.char这个类下面.

# 基本都返回ndarray对象.
# 默认都是对ndarray中的元素进行操作, 也就是对元素进行操作, 每个元素是一个字符串.
# add(): 对两个数组的元素进行字符串连接.
# multiply(): 返回按照元素多重连接后的字符串.
# center(): 将字符串居中, 并使用指定字符串在左侧和右侧进行填充.
# capitalize(): 将字符串中第一个字符转换为大写.
# title(): 将字符串中每个单词的第一个字母转换为大写
# lower(): 数组元素转换为小写.
# upper(): 数组元素转换为大写
# split(): 指定分隔符对字符串进行凤娥, 并返回数组列表.
# splitlines(): 返回元素中的行列表, 以换行符分割.
# strip(): 移除元素开头或者结尾处的指定字符.
# join(): 通过指定分隔符来连接数组中的元素.
# replace(): 使用新字符串替代字符串当中所有的子字符串.
# encode(): 编码, 数组元素会依次调用str.encode
# decode(): 解码, 数组元素会依次调用str.decode.

In [4]:
import numpy as np

print(np.char.add(["sunck"], ["good"]))
print(np.char.add(["sunck", "kaiming"], ["good", "job"]))



['sunckgood']
['sunckgood' 'kaimingjob']


In [6]:
print(np.char.multiply("good", 3))

goodgoodgood


In [12]:
print(np.char.center(["nice", "handsome", "bilibilibiliworinimafadjkflajkfakl"], 20, fillchar="*"))
# 就是每个元素居中显示, 总宽度20, 使用fillchar进行填充, 超过的会截断.

['********nice********' '******handsome******' 'bilibilibiliworinima']


In [14]:
print(np.char.capitalize(["sunck is a good man", "kaige is a nice man"]))

['Sunck is a good man' 'Kaige is a nice man']


In [15]:
print(np.char.title(["sunck is a good man", "kaige is a nice man"]))

['Sunck Is A Good Man' 'Kaige Is A Nice Man']


In [16]:
print(np.char.lower(["sunck is a good man", "kaige is a nice man"]))

['sunck is a good man' 'kaige is a nice man']


In [17]:
print(np.char.upper(["sunck is a good man", "kaige is a nice man"]))

['SUNCK IS A GOOD MAN' 'KAIGE IS A NICE MAN']


In [19]:
print(np.char.split(["sunck is a good man", "kaige is a nice man"], " "))
# 得到了一个列表. 按照空格' '进行切割. 然后返回ndarray元素, 里面是个列表, 实际上就是遍历这个数组, 然后对其中的元素应用split.

[list(['sunck', 'is', 'a', 'good', 'man'])
 list(['kaige', 'is', 'a', 'nice', 'man'])]


In [21]:
print(np.char.splitlines(["sunck is a \ngood man", "kaige is a nice man"]))

[list(['sunck is a ', 'good man']) list(['kaige is a nice man'])]


In [23]:
print(np.char.strip(["**sunck is a good man****", "kaige is a nice man****"], "*"))
# 移除*.

['sunck is a good man' 'kaige is a nice man']


In [26]:
print(np.char.join("-", ["nice", "good"]))
print(np.char.join(["-", '.'], ["nice", "good"]))


['n-i-c-e' 'g-o-o-d']
['n-i-c-e' 'g.o.o.d']


In [27]:
print(np.char.replace(["sunck is a good man", "kaige is a nice man"], ["good", "nice"], "fuck"))
# 针对第一个句子good替换为fuck, 第二个元素nice替换fuck.让然你也可更换.

['sunck is a fuck man' 'kaige is a fuck man']


In [33]:
a = np.char.encode(["such"], encoding="utf-8")
print(a)
# 编码, 字节流.

[b'such']


In [35]:
print(np.char.decode(a, encoding="utf-8"))
# 解码. 变成字符数组.

['such']


In [38]:
# 数学函数:
# 标准三角函数: sin(), cos(), tan()
# 都在np中.
# np.sin(弧度制) # 这里的数值是弧度制. 也就是角度*pi, 然后除以180
# 弧度制/pi = 角度制/180.

import numpy as np

a = np.array([0, 30, 45, 60, 90])
print("不同角度的正弦值")
print(np.sin(a * np.pi / 180))

print("不同角度的cos值")
print(np.cos(a * np.pi / 180))

print("不同角度的正切值")
print(np.tan(a * np.pi / 180))

不同角度的正弦值
[0.         0.5        0.70710678 0.8660254  1.        ]
不同角度的cos值
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
不同角度的正切值
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [46]:
# 反三角函数: arcsin(), arccos(), arctan()
# 从弧度制, 返回弧度制值.
a = np.array([0, 30, 45, 60, 90])

b = np.sin(a * np.pi / 180)
inv = np.arcsin(b) # 以弧度为单位.
# 然后转换为角度值来查看结果:
print(np.degrees(inv)) # 转换为角度值.
print(inv*180/np.pi) # 一个道理.

# 同理, 其他的反三角函数也是同理.
# 这里不在演示.

[ 0. 30. 45. 60. 90.]
[ 0. 30. 45. 60. 90.]


In [50]:
# 其他函数:
# around(): 返回指定数字的四舍五入数值
# 就是原生python中的round函数, array round同理
# np.around(a, decimals=0)
# a: 数组, 对数组中的每个元素进行运算
# decimals: 舍的小数位.默认为0, 如果为负, 整数将四舍五入到小数点左侧的位置.
x = np.array([1.0, 1.45, 1.60])
print(np.around(x))
print(np.around(x, 1)) # 就是在小数点右边一位,进行四舍五入.
print(np.around(x, -1)) # 就是在小数点左边一位, 进行四舍五入.



[1. 1. 2.]
[1.  1.4 1.6]
[0. 0. 0.]


In [53]:
# floor(): 向下取整. 返回不大于输入参数的最大整数.#
# 即标量x的下限是最大的整数i, 使得i <= x.注意在python中, 向下取整总是从0设入.
# ceil(): 向上取整, 返回输入值的上限, 即标量x的上线是最小的整数i, 使得i >= x..
print(x)
print(np.floor(x))
print(np.ceil(x))


[1.   1.45 1.6 ]
[1. 1. 1.]
[1. 2. 2.]


In [2]:
# 算数函数：
# add(), subtract(), multiply(), divide()
# 相加, 相减, 相乘, 相除.

import numpy as np

x = np.arange(9, dtype=np.float32).reshape((3, 3))
y = np.array([10, 10, 10])
print(x)
print(y)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[10 10 10]


In [5]:
print(np.add(x, y))
# 广播, 然后相加.
print(x + y) # 默认是对元素进行操作.
# 结果一样

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [6]:
print(np.subtract(x, y))
print(x - y)

[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


In [8]:
print(np.multiply(x, y))

print(x * y)

[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [9]:
print(np.divide(x, y))
print(x / y)
# 实际上就是对运算符号进行重载了, 在针对array类型的时候.

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [15]:
# reciprocal(): 返回数组元素的倒数
# power(): 将第一个输入数组中的元素作为底数, 然后计算他与第二个输入数组中相应元素的幂, 可以进行广播.
# mod(), remainder(). 计算输入数组中相应元素的相除后的余数.

x = np.array([0.25, 0.5, 1, 100])
print(x)
print(np.reciprocal(x)) # 每个元素进行倒数.


[  0.25   0.5    1.   100.  ]
[4.   2.   1.   0.01]


In [16]:

x = np.array([2, 3, 4])
y = np.array([1, 2, 3])
print(np.power(x, y))
print(x ** y) # 同理操作.
print(np.power(x, 2)) # x的所有元素平方.
print(x ** 2) # 同理操作.

[ 2  9 64]
[ 2  9 64]
[ 4  9 16]
[ 4  9 16]


In [18]:
x = np.array([10, 10, 10])
y = np.array([2, 3, 4])

print(np.mod(x, y))
print(np.remainder(x, y))
# 得到的余数.

[0 1 2]
[0 1 2]


In [32]:
# 统计函数:
# amax(array, axis=None), amin()
# 计算数组中的元素沿指定轴的最大值, 最小值. 默认是看整个数组.
# ptp(): 计算数组中元素最大值与最小值的差(最大值-最小值)
import numpy as np
x = np.random.randint(1, 11, 9).reshape((3, 3))
print(x)

[[ 7  9  7]
 [ 8 10  3]
 [ 8  4  8]]


In [36]:
print(x)
print(np.amax(x, axis=0)) # 以行为元素, 比较列..
print(np.amax(x, axis=1)) # 以列为元素, 比较行.
print(np.amin(x)) # 整个数组最小值.

[[ 7  9  7]
 [ 8 10  3]
 [ 8  4  8]]
[ 8 10  8]
[ 9 10  8]
3


In [35]:
print(x)
print(np.ptp(x)) # 最大值 - 最小值.

print(np.ptp(x, axis=0)) # axis=0, 元素是每行的数组. 所以比较的是列
print(np.ptp(x, axis=1)) #  按照一行, 每行的最大值和最小值相减.


[[ 7  9  7]
 [ 8 10  3]
 [ 8  4  8]]
7
[1 6 5]
[2 7 4]


In [38]:
# percentile(a, p, axis)
# 百分位是统计使用的度量, 表示小于这个值的观察值的百分比.
# a: 输入数组,
# p: 要计算的百分比数, 在0-100之间
# axis: 沿着它计算百分比数的轴.

print(x)
print(np.percentile(x, 50)) # 也就是50%的那个数值, 是8.0

[[ 7  9  7]
 [ 8 10  3]
 [ 8  4  8]]
8.0


In [47]:
# median(): 计算数组中元素的中位数(中值)
# mean(): 返回数组元素中的算数平均数, 如果提供了轴, 则按照轴计算.
# average(): 根据另一个数组给出的权重计算数组中元素的加权平均值, 可以接受一个轴参数. 如果没有指定轴, 则数组会被自动展开.

# 加权平均值: 将各数组乘以相对应的权数, 然后加总求和得到总体值, 再除以总的单位数.
# 例如: [1, 2, 3, 4], 权重[4, 3, 2, 1], 对应元素相乘然后相加, 然后除以权重相加.: (1*4+2*3+3*2+4*1)/(4+3+2+1)

x = np.array([1,2,3,4])
print(x)
weight = np.array([4, 3, 2, 1])
print(np.average(x)) # x的平均值

print(np.average(x, weights=weight))

# 如果returned=True, 则返回权重的和. 也就是分母.
print(np.average(x, weights=weight, returned=True))
# 返回一个元组, 第一个是加权平均值, 第二个是权重的和.

# 也能在多维数组中使用.

[1 2 3 4]
2.5
2.0
(2.0, 10.0)


In [50]:
# 标准差.
# 标准差是一组数据平均值分散程度的一种度量.
# 标准差是方差的算数平方根.
# std = sqrt(mean((x - x.mead())**2)).
# np.std(a, axis=None)
print(np.std(np.array([1, 2, 3, 4])))







1.118033988749895


In [51]:
# 方差: 统计中的方差(样本方差)是每个样本值与全体样本值的平均数之差的平方值的平均数, 即: mean((x - x.mean()) ** 2. 换句话说, 标准差是方差的平方根.
# np.var()

print(np.var(x))




1.25
