In [6]:
import numpy as np


# 拷贝: 三种拷贝:
# 赋值, 视图, 副本.
# 简单的赋值不会创建数组对象的副本(不会深拷贝, 只是引用, 指向). 相反, 它使用原数组的相同id()来访问它.id()返回Python对象通用的标识符, 类似于C中的指针.

x = np.arange(6).reshape(2, 3)
print(x)
print(id(x))

print("===" * 10)
y = x
print(y)
print(id(y))

# 可见, 内容, 地址都是一样的. 说明.x和y都指向堆区的那个数组.

y.shape=(3,2)
x.shape # 也变化了.

[[0 1 2]
 [3 4 5]]
2944735801136
[[0 1 2]
 [3 4 5]]
2944735801136


(3, 2)

In [12]:
# 视图: 又可成为浅拷贝, 是数据的一个别称或者引用, 通过该名称或者引用, 即可以访问, 操作原有数据, 但原有数据不会产生拷贝(不是深拷贝, 还是浅拷贝). 对视图进行修改, 他会影响原始数据, 因为是同一个物理内存.
# 这有点类似于子集的概念.


# 发生情况: numpy的切片操作会返回元数据的视图, 修改数据则会影响到原始数组.
x = np.arange(12)
print(x)

# 切片数组:
y = x[3:]
print(y) # 这就是x的一个视图. 有点类似于子集的概念.

y[1] = 400
print(y)
print(x)

print(id(x))
print(id(y)) # 这是一个视图
print(id(x[3:])) # 产生一个另一个视图, 视图和前面的视图地址不一样.
# 地址是不一样的


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11]
[  3 400   5   6   7   8   9  10  11]
[  0   1   2   3 400   5   6   7   8   9  10  11]
2944720556560
2944753077200
2944739440272


In [25]:
# ndarray.view()函数产生一个视图.
# 创建一个新的数组对象, 该方法创建的新数组的维数更改不会更改原始数据的维数.
# print(x.reshape(3, 4))
x = np.arange(6).reshape(2,3)
print(x)


y = x.view()
print(y)

y[1][0] = 200

print(y)
print(x)
# 都变了
y.shape = (3, 2)
print(y.shape)
print(x.shape) # 但是形状没有改的.


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[  0   1   2]
 [200   4   5]]
[[  0   1   2]
 [200   4   5]]
(3, 2)
(2, 3)


In [30]:
# 副本: 又可以称为深拷贝, 是一个数据的完整的拷贝, 如果我们对副本进行修改, 它不会影响到原始数据, 不是同一个物理内存.

# 发生情况:
# 调用ndarray的copy()函数会产生一个副本.
# 创建一个副本. 是重新copy一份.

y = x.copy()
print(y)

y[0][0] = 100
print(y)
print(x)
# x没有变化



import copy

copy.deepcopy() # 这个函数也同样是可以达到深拷贝的效果.


[[  0   1   2]
 [200   4   5]]
[[100   1   2]
 [200   4   5]]
[[  0   1   2]
 [200   4   5]]
